
package ipc.proyecto1;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class VerUsuariosFrame extends javax.swing.JFrame {

    public VerUsuariosFrame() {
        initComponents();
        llenarTablaUsuario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        CerrarButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        UsuarioTable = new javax.swing.JTable();
        DeleteUsuarioButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel3.setText("Usuarios Registrados");

        CerrarButton.setText("Regresar");
        CerrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarButtonActionPerformed(evt);
            }
        });

        UsuarioTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Correo", "Nombre", "Apellido", "Fecha de Nacimiento", "DPI", "Nacionalidad", "Teléfono", "Género", "Alías", "Rol"
            }
        ));
        UsuarioTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(UsuarioTable);
        if (UsuarioTable.getColumnModel().getColumnCount() > 0) {
            UsuarioTable.getColumnModel().getColumn(0).setPreferredWidth(50);
            UsuarioTable.getColumnModel().getColumn(1).setPreferredWidth(50);
            UsuarioTable.getColumnModel().getColumn(2).setPreferredWidth(50);
            UsuarioTable.getColumnModel().getColumn(3).setPreferredWidth(70);
            UsuarioTable.getColumnModel().getColumn(4).setPreferredWidth(50);
            UsuarioTable.getColumnModel().getColumn(5).setPreferredWidth(50);
            UsuarioTable.getColumnModel().getColumn(6).setPreferredWidth(50);
            UsuarioTable.getColumnModel().getColumn(7).setPreferredWidth(50);
            UsuarioTable.getColumnModel().getColumn(8).setPreferredWidth(50);
            UsuarioTable.getColumnModel().getColumn(9).setPreferredWidth(50);
        }

        DeleteUsuarioButton.setText("Eliminar Usuario");
        DeleteUsuarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteUsuarioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1034, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CerrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(454, 454, 454))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(DeleteUsuarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(458, 458, 458))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DeleteUsuarioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(CerrarButton)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CerrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarButtonActionPerformed
        AdministradorFrame admin = new AdministradorFrame();
        admin.setVisible(true);
        dispose();
    }//GEN-LAST:event_CerrarButtonActionPerformed

    private void DeleteUsuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteUsuarioButtonActionPerformed
        int eliminarFila = UsuarioTable.getSelectedRow();
        
        if (eliminarFila >=0){
            AppState.usuarios.remove(eliminarFila);
            llenarTablaUsuario();
        }
    }//GEN-LAST:event_DeleteUsuarioButtonActionPerformed

    private void llenarTablaUsuario(){
        
        DefaultTableModel modeloDafault = new DefaultTableModel(new String[]{"Correo" , "Nombre" , "Apellido" , "DPI", "Nacionalidad", "Telefono", "Genero", "Rol", "Fecha", "Contraseña", "Kiosco", "Imagen"},AppState.usuarios.size());
        UsuarioTable.setModel(modeloDafault);
    
       TableModel modeloDatos = UsuarioTable.getModel();
       for(int i = 0; i < AppState.usuarios.size(); i++){
          modeloDatos.setValueAt(AppState.usuarios.get(i).getCerreo(),i,0);
          modeloDatos.setValueAt(AppState.usuarios.get(i).getNombre(),i,1); 
          modeloDatos.setValueAt(AppState.usuarios.get(i).getApellido(),i,2); 
          modeloDatos.setValueAt(AppState.usuarios.get(i).getDpi(),i,3); 
          modeloDatos.setValueAt(AppState.usuarios.get(i).getNacionalida(),i,4); 
          modeloDatos.setValueAt(AppState.usuarios.get(i).getTelefono(),i,5); 
          modeloDatos.setValueAt(AppState.usuarios.get(i).getGenero(),i,6); 
          modeloDatos.setValueAt(AppState.usuarios.get(i).getRol(),i,7); 
          modeloDatos.setValueAt(AppState.usuarios.get(i).getFecha(),i,8); 
          modeloDatos.setValueAt(AppState.usuarios.get(i).getContrasena(),i,9); 
          //modeloDatos.setValueAt(AppState.usuarios.get(i).getCerreo(),i,10); 
          //modeloDatos.setValueAt(AppState.usuarios.get(i).getCerreo(),i,11); 
       }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerUsuariosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerUsuariosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerUsuariosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerUsuariosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerUsuariosFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CerrarButton;
    private javax.swing.JButton DeleteUsuarioButton;
    private javax.swing.JTable UsuarioTable;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
