
package ipc.proyecto1;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;

public class PedidosFrame extends javax.swing.JFrame {

    static int codigo = 1;

    public PedidosFrame() {
        initComponents();

        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Cotización");

        PagobuttonGroup.add(ContraEntregaRadioButton);
        PagobuttonGroup.add(TarjetaRadioButton);

        for (int i = 0; i < Proyecto1.departamentos.size(); i++) {
            Departamentos name = Proyecto1.departamentos.get(i);
            OrigenDepartamentoComboBox.addItem(name.getNameDep());
            DestinoDepartamentoComboBox.addItem(name.getNameDep());
        }
        for (int m = 0; m < Proyecto1.municipios.size(); m++) {
            Municipio name = Proyecto1.municipios.get(m);
            OrigenMunicipioComboBox.addItem(name.getNameMunicipio());
            DestinoMunicipioComboBox.addItem(name.getNameMunicipio());
        }

        for (int n = 0; n < AppState.usuarioLogeado.facturas.size(); n++) {
            ContenedorFactura facturas = AppState.usuarioLogeado.facturas.get(n);
            DatosFacturaComboBox.addItem(facturas.getNit());

        }

        /*
        OrigenDepartamentoComboBox.addActionListener((ActionEvent e) -> {
            for (Departamentos ci : Proyecto1.municipios){
                if (OrigenDepartamentoComboBox.getSelectedItem().toString().equals(ci.nombre)) {
                    ImageIcon imagenRedimensionadaIcon = new ImageIcon(imagenRedimensionada);
                    imagenLabel.setIcon(imagenRedimensionadaIcon);
                    break;
                }
            }
        });*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PagobuttonGroup = new javax.swing.ButtonGroup();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        NumPaquetesTextField = new javax.swing.JTextField();
        CotizarTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CotizarButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        CerrarButton = new javax.swing.JButton();
        OrigenDepartamentoComboBox = new javax.swing.JComboBox<>();
        DestinoDepartamentoComboBox = new javax.swing.JComboBox<>();
        OrigenMunicipioComboBox = new javax.swing.JComboBox<>();
        DestinoMunicipioComboBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        TamañoComboBox = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        DatosFacturaComboBox = new javax.swing.JComboBox<>();
        RealizarPagoButton = new javax.swing.JButton();
        TotalTextField = new javax.swing.JTextField();
        ServicioComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        ContraEntregaRadioButton = new javax.swing.JRadioButton();
        TarjetaRadioButton = new javax.swing.JRadioButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 150), new java.awt.Dimension(0, 150), new java.awt.Dimension(32767, 150));
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cancelenvioButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton3.setText("Descargar Guía");

        jLabel10.setText("Tamaño de Paquete:");

        CotizarTextField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CotizarTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CotizarTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CotizarTextFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Tipo de Pago:");

        jLabel2.setText("ORIGEN:");

        jLabel4.setText("DESTINO:");

        jLabel5.setText("No. de Paquetes:");

        CotizarButton.setText("Cotizar");
        CotizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CotizarButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Descargar Factura");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        CerrarButton.setText("Regresar");
        CerrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarButtonActionPerformed(evt);
            }
        });

        OrigenDepartamentoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrigenDepartamentoComboBoxActionPerformed(evt);
            }
        });

        jLabel9.setText("Departamento:");

        jLabel12.setText("Departamento:");

        jLabel13.setText("Municipio:");

        jLabel14.setText("Municipio:");

        TamañoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pequeño   (1 a 10   Libras)", "Mediano   (11 a 50   Libras)", "Grande   ( + 51   Libras)" }));

        jLabel15.setText("DATOS DE FACTURACIÓN:");

        RealizarPagoButton.setText("REALIZAR PAGO Y ENVIAR");
        RealizarPagoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RealizarPagoButtonActionPerformed(evt);
            }
        });

        TotalTextField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TotalTextField.setForeground(new java.awt.Color(204, 0, 0));
        TotalTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ServicioComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estándar", "Especial" }));

        jLabel1.setText("Tipo de Servicio:");

        ContraEntregaRadioButton.setText("COBRO CONTRA ENTREGA");
        ContraEntregaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraEntregaRadioButtonActionPerformed(evt);
            }
        });

        TarjetaRadioButton.setText("COBRO A MI CUENTA");

        filler2.setBackground(new java.awt.Color(51, 51, 51));
        filler2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Cobro adicional de Q.5.00");

        jLabel7.setText("Pago con tarjeta de crédito o débito");

        cancelenvioButton.setText("Cancelar Envío");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(OrigenMunicipioComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(207, 207, 207))
                    .addComponent(jLabel10)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(OrigenDepartamentoComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DestinoMunicipioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(DestinoDepartamentoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(TamañoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NumPaquetesTextField))
                    .addComponent(jLabel1)
                    .addComponent(ServicioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(CotizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CerrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CotizarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(169, 169, 169)
                                .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ContraEntregaRadioButton)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(TotalTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(DatosFacturaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton3))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cancelenvioButton)
                                        .addGap(68, 68, 68))))
                            .addComponent(jLabel6)
                            .addComponent(TarjetaRadioButton)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7))))
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(RealizarPagoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(ContraEntregaRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TarjetaRadioButton)
                                .addGap(2, 2, 2)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(OrigenDepartamentoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DestinoDepartamentoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DestinoMunicipioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(OrigenMunicipioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NumPaquetesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TamañoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ServicioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CotizarButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CotizarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DatosFacturaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(RealizarPagoButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TotalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton2)
                                    .addComponent(jButton3))
                                .addGap(28, 28, 28)
                                .addComponent(cancelenvioButton)
                                .addGap(38, 38, 38))))
                    .addComponent(filler2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53)
                .addComponent(CerrarButton)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CerrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarButtonActionPerformed
        UsuarioFrame usuario = new UsuarioFrame();
        usuario.setVisible(true);
        dispose();
    }//GEN-LAST:event_CerrarButtonActionPerformed


    private void CotizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CotizarButtonActionPerformed

        try {

            String codeDepDestino = DestinoDepartamentoComboBox.getSelectedItem().toString();
            String servicio = ServicioComboBox.getSelectedItem().toString();
            String tamaño = TamañoComboBox.getSelectedItem().toString();

            //*Double precioEstandarDouble = Double.valueOf(PrecioEstandarTextField.getText());
            Double cantidad = Double.valueOf(NumPaquetesTextField.getText());

            if (!NumPaquetesTextField.getText().equals("")) {
                for (int i = 0; i < Proyecto1.departamentos.size(); i++) {
                    Departamentos departamentos = Proyecto1.departamentos.get(i);
                    String name = Proyecto1.departamentos.get(i).getNameDep();

                    if (name.equals(codeDepDestino)) {
                        String code = departamentos.getCodigoRegistro();
                        for (int o = 0; o < Proyecto1.regiones.size(); o++) {
                            Regiones region = Proyecto1.regiones.get(o);
                            String coderegion = region.getCode();
                            if (code.equals(coderegion)) {

                                if (ServicioComboBox.getSelectedItem().equals("ESTANDAR")) {
                                    Double estandar = region.getEstandar();
                                    System.out.println(estandar);
                                    if (TamañoComboBox.getSelectedItem().equals("PEQUÑO    (1 a 10   (Libras))")) {

                                        Double total;

                                        total = estandar * cantidad * 10;
                                        System.out.println(total);

                                        CotizarTextField.setText(String.valueOf(total));

                                        break;
                                    }
                                    if (TamañoComboBox.getSelectedItem().equals("MEDIANO  (11 a 50 (Libras))")) {

                                        Double total;

                                        total = estandar * cantidad * 15;
                                        System.out.println(total);
                                        CotizarTextField.setText(String.valueOf(total));
                                        break;
                                    }
                                    if (TamañoComboBox.getSelectedItem().equals("GRANDE     ( + 51    (Libras))")) {

                                        Double total;

                                        total = estandar * cantidad * 20;
                                        System.out.println(total);
                                        CotizarTextField.setText(String.valueOf(total));
                                        break;
                                    }

                                } else if (ServicioComboBox.getSelectedItem().equals("ESPECIAL")) {
                                    Double especial = region.getEspecial();
                                    System.out.println(especial);
                                    if (TamañoComboBox.getSelectedItem().equals("PEQUÑO    (1 a 10   (Libras))")) {

                                        Double total;

                                        total = especial * cantidad * 10;
                                        System.out.println(total);
                                        CotizarTextField.setText(String.valueOf(total));
                                        break;
                                    }
                                    if (TamañoComboBox.getSelectedItem().equals("MEDIANO  (11 a 50 (Libras))")) {

                                        Double total;

                                        total = especial * cantidad * 15;
                                        System.out.println(total);
                                        CotizarTextField.setText(String.valueOf(total));
                                        break;
                                    }
                                    if (TamañoComboBox.getSelectedItem().equals("GRANDE     ( + 51    (Libras))")) {

                                        Double total;
                                        total = especial * cantidad * 20;
                                        System.out.println(total);
                                        CotizarTextField.setText(String.valueOf(total));
                                        break;
                                    }
                                }

                            }

                        }

                        /*for (int e = 0; e < Proyecto1.municipios.size(); e++) {
                        Municipio muni = Proyecto1.municipios.get(i);
                        if (code.equals(muni.getCodeDep())) {
                            OrigenMunicipioComboBox.addItem(muni.getNameMunicipio());
                            System.out.println(muni);
                        }
                    }*/
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Rellenar Todos los datos!", "Alerta", JOptionPane.WARNING_MESSAGE);
            }
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Posiblemente no exite Origen o Destino!", "Alerta", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_CotizarButtonActionPerformed

    private void OrigenDepartamentoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrigenDepartamentoComboBoxActionPerformed

        String depOrigen = OrigenDepartamentoComboBox.getSelectedItem().toString();

        if (evt.equals(OrigenDepartamentoComboBox.getSelectedItem())) {
            for (int i = 0; i < Proyecto1.departamentos.size(); i++) {
                Departamentos departamentos = Proyecto1.departamentos.get(i);
                String name = departamentos.getNameDep();
                if (name.equals(depOrigen)) {
                    String code = departamentos.codigoDep;
                    for (int e = 0; e < Proyecto1.municipios.size(); e++) {
                        Municipio municipio = Proyecto1.municipios.get(i);
                        String codeMunDep = municipio.getCodeDep();
                        if (code.equals(codeMunDep)) {
                            OrigenDepartamentoComboBox.removeAllItems();
                            OrigenMunicipioComboBox.addItem(municipio.getNameMunicipio());
                        }
                    }

                }
            }
        }
    }//GEN-LAST:event_OrigenDepartamentoComboBoxActionPerformed

    private void CotizarTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CotizarTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CotizarTextFieldActionPerformed

    private void RealizarPagoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RealizarPagoButtonActionPerformed

        try {
            String codeDepDestino = DestinoDepartamentoComboBox.getSelectedItem().toString();
            String servicio = ServicioComboBox.getSelectedItem().toString();
            String tamaño = TamañoComboBox.getSelectedItem().toString();
            Double cantidad = Double.valueOf(NumPaquetesTextField.getText());

            if (!NumPaquetesTextField.getText().equals("")) {
                for (int i = 0; i < Proyecto1.departamentos.size(); i++) {
                    Departamentos departamentos = Proyecto1.departamentos.get(i);
                    String name = Proyecto1.departamentos.get(i).getNameDep();
                    if (name.equals(codeDepDestino)) {
                        String code = departamentos.getCodigoRegistro();
                        for (int o = 0; o < Proyecto1.regiones.size(); o++) {
                            Regiones region = Proyecto1.regiones.get(o);
                            String coderegion = region.getCode();
                            if (code.equals(coderegion)) {

                                float cargo = 0;

                                if (ContraEntregaRadioButton.isSelected() == true) {

                                    cargo = 5;

                                } else if (TarjetaRadioButton.isSelected() == true) {
                                    cargo = 0;
                                } else {
                                    JOptionPane.showMessageDialog(null, "Elegir el metodo de Pago!", "Alerta", JOptionPane.WARNING_MESSAGE);
                                    break;
                                }

                                if (ServicioComboBox.getSelectedItem().equals("ESTANDAR")) {
                                    Double estandar = region.getEstandar();
                                    System.out.println(estandar);
                                    if (TamañoComboBox.getSelectedItem().equals("PEQUÑO    (1 a 10   (Libras))")) {

                                        Double total;

                                        total = estandar * cantidad * 10 + cargo;
                                        System.out.println(total);

                                        TotalTextField.setText(String.valueOf(total));
                                        registrarFacGuia();
                                        
                                        System.out.println();
                                        break;
                                    }
                                    if (TamañoComboBox.getSelectedItem().equals("MEDIANO  (11 a 50 (Libras))")) {

                                        Double total;

                                        total = estandar * cantidad * 15 + cargo;
                                        System.out.println(total);
                                        TotalTextField.setText(String.valueOf(total));
                                        registrarFacGuia();
                                        break;
                                    }
                                    if (TamañoComboBox.getSelectedItem().equals("GRANDE     ( + 51    (Libras))")) {

                                        Double total;

                                        total = estandar * cantidad * 20 + cargo;
                                        System.out.println(total);
                                        TotalTextField.setText(String.valueOf(total));
                                        registrarFacGuia();
                                        break;
                                    }

                                } else if (ServicioComboBox.getSelectedItem().equals("ESPECIAL")) {
                                    Double especial = region.getEspecial();
                                    System.out.println(especial);
                                    if (TamañoComboBox.getSelectedItem().equals("PEQUÑO    (1 a 10   (Libras))")) {

                                        Double total;

                                        total = especial * cantidad * 10 + cargo;
                                        System.out.println(total);
                                        TotalTextField.setText(String.valueOf(total));
                                        registrarFacGuia();
                                        break;
                                    }
                                    if (TamañoComboBox.getSelectedItem().equals("MEDIANO  (11 a 50 (Libras))")) {

                                        Double total;

                                        total = especial * cantidad * 15 + cargo;
                                        System.out.println(total);
                                        TotalTextField.setText(String.valueOf(total));
                                        registrarFacGuia();
                                        break;
                                    }
                                    if (TamañoComboBox.getSelectedItem().equals("GRANDE     ( + 51    (Libras))")) {

                                        Double total;

                                        total = especial * cantidad * 20 + cargo;
                                        System.out.println(total);
                                        TotalTextField.setText(String.valueOf(total));
                                        registrarFacGuia();
                                        break;
                                    }
                                }

                            }

                        }
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Rellenar Todos los datos!", "Alerta", JOptionPane.WARNING_MESSAGE);
            }
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Posiblemente no exite Origen o Destino!", "Alerta", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_RealizarPagoButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Factura f = AppState.usuarioLogeado.facturasdatos.get(0);
        System.out.println(f.getNumFactura()+f.getCodePaquete()+f.getOrigenDertamento() +f.getOrigenMunicipio()+f.getDestinoDepartamento()+f.getDestinoMunicipio()+f.getNit()+f.getTypePago()+f.getTamañoP()+f.getNumPaquetes()+f.getTotal());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ContraEntregaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraEntregaRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraEntregaRadioButtonActionPerformed

    private void registrarFacGuia() {
        try {
            int numFactura = codigo++;
            String codigoP = "3jX-";
            String DepOrigen = OrigenDepartamentoComboBox.getSelectedItem().toString();
            String MuniOrigen = OrigenMunicipioComboBox.getSelectedItem().toString();
            String DepDestino = DestinoDepartamentoComboBox.getSelectedItem().toString();
            String MuniDestino = DestinoMunicipioComboBox.getSelectedItem().toString();
            String nit = DatosFacturaComboBox.getSelectedItem().toString();
            String tipoPago = ContraEntregaRadioButton.isSelected() ? "Contra Entrega" : "Tarjeta";
            String tamano = TamañoComboBox.getSelectedItem().toString();
            Double cantidad = Double.valueOf(NumPaquetesTextField.getText());
            
            //Double precioEstandarDouble = Double.valueOf(PrecioEstandarTextField.getText());
           Double total = Double.valueOf(TotalTextField.getText());

            Factura f = new Factura(numFactura, codigoP, DepOrigen, MuniOrigen, DepDestino, MuniDestino,nit, tipoPago,tamano,cantidad,total);
            AppState.usuarioLogeado.agregarDatosFacuturas(f);

            UsuarioFrame usuario = new UsuarioFrame();
            usuario.setVisible(true);
            dispose();
            JOptionPane.showMessageDialog(null, "Tarjeta Registrada!", "Alerta", JOptionPane.WARNING_MESSAGE);

        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error inesperado!", "Alerta", JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PedidosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PedidosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PedidosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PedidosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PedidosFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CerrarButton;
    private javax.swing.JRadioButton ContraEntregaRadioButton;
    private javax.swing.JButton CotizarButton;
    private javax.swing.JTextField CotizarTextField;
    private javax.swing.JComboBox<String> DatosFacturaComboBox;
    private javax.swing.JComboBox<String> DestinoDepartamentoComboBox;
    private javax.swing.JComboBox<String> DestinoMunicipioComboBox;
    private javax.swing.JTextField NumPaquetesTextField;
    private javax.swing.JComboBox<String> OrigenDepartamentoComboBox;
    private javax.swing.JComboBox<String> OrigenMunicipioComboBox;
    private javax.swing.ButtonGroup PagobuttonGroup;
    private javax.swing.JButton RealizarPagoButton;
    private javax.swing.JComboBox<String> ServicioComboBox;
    private javax.swing.JComboBox<String> TamañoComboBox;
    private javax.swing.JRadioButton TarjetaRadioButton;
    private javax.swing.JTextField TotalTextField;
    private javax.swing.JButton cancelenvioButton;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

}
